set windows-powershell := true


fix:
	cargo clippy --workspace --all-features --fix --allow-dirty --allow-staged

fmt:
	cargo fmt --all


cp-all-openssl-build:
	just cp-openssl-build x86_64
	just cp-openssl-build aarch64

cp-openssl-build arch:
	rm -rf openssl-prebuild/{{arch}}/*
	cp -r target/{{arch}}-linux-android/release/build/openssl-sys-*/out/openssl-build/install openssl-prebuild/{{arch}}
	zip -r install.zip openssl-prebuild/{{arch}}/install
	mv install.zip openssl-prebuild/{{arch}}


unzip-all:
	just unzip x86_64
	just unzip aarch64

unzip arch:
	unzip openssl-prebuild/{{arch}}/install.zip

clean:
	cargo clean