name: Build Git

on:
  workflow_dispatch:
    inputs:
      ARCH:
        description: "arch"
        type: choice
        required: false
        default: "arm64-v8a"
        options:
          - arm64-v8a
          - x86_64
          - armeabi-v7a
          - x86

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          git clone https://github.com/wiiznokes/libgit2-android --depth=1 --branch=patch-android app/libgit2-android
          git -C app/libgit2-android submodule update --init
          ANDROID_API=34 ANDROID_ABI=$INPUT_ARCH BUILD_ALL=1 INSTALL_NDK=1 JNI_LIBS_PATH=artifacts ./build.sh

      - uses: actions/upload-artifact@v4
        with:
          name: libs-${{ env.INPUT_ARCH }}
          path: |
            artifacts/
