name: Build-Apk

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: "App version"
      is_nightly:
        description: "Is nightly"
        type: boolean
        required: true
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      is_nightly:
        description: "Is nightly"
        type: boolean
        required: true

concurrency:
  group: ${{ github.workflow }}-build-apk
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          submodules: recursive

      # - name: Build Libgit2
      #   run: |
      #     cd app/libgit2-android
      #     ANDROID_API=34 ANDROID_ABI=arm64-v8a BUILD_ALL=1 INSTALL_NDK=1 ./build.sh
      #     ANDROID_API=34 ANDROID_ABI=x86_64 BUILD_ALL=1 CLEAN=1 ./build.sh

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle

      # https://github.com/actions/cache/blob/main/examples.md#java---gradle
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - if: ${{ github.event.inputs.is_nightly == 'false' }}
        name: Retrieve the secret and decode it to a file, and Build release apk
        env:
          KEY_BASE64: ${{ secrets.KEY_BASE64 }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          echo $KEY_BASE64 | base64 --decode > app/key.jks
          ./gradlew assembleRelease
          echo "APP_VARIANT=release" >> $GITHUB_ENV

      - if: ${{ (github.event.inputs.is_nightly  == 'true') || (github.event.inputs.is_nightly  == '') }}
        name: Build nightly apk
        run: |
          ./gradlew assembleNightly
          echo "APP_VARIANT=nightly" >> $GITHUB_ENV

      - run: |
          mkdir -p packages

          # warning: do not use github.event syntax here
          # https://stackoverflow.com/questions/71458189/github-action-workflow-call-does-not-use-up-to-date-input-values
          mv app/build/outputs/apk/${{ env.APP_VARIANT }}/app-release.apk packages/gitnote-${{ env.APP_VARIANT }}-${{ inputs.version }}.apk

      - uses: actions/upload-artifact@v4
        with:
          name: releases
          path: packages/*
          if-no-files-found: error
